#include <stdint.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "esp_check.h"
#include "sdkconfig.h"
#include "soc/i2s_struct.h"
#include "soc/rtc.h"


// 40 MHz output without gaps
// outputs 4 bytes with CS low, then 4 bytes with CS high
// invert one of the CS lines so that this can drive 2x MCP4822 DACs

#define I2S I2S_NUM_1
#define EXAMPLE_BUFF_SIZE               1024 * 8

static i2s_chan_handle_t                tx_chan;        // I2S tx channel handler

static void i2s_example_write_task(void *args)
{
	unsigned cnt = 0;
	uint8_t *w_buf = (uint8_t *)calloc(1, EXAMPLE_BUFF_SIZE);
	assert(w_buf);  // Check if w_buf allocation success

	size_t w_bytes = EXAMPLE_BUFF_SIZE;

	/* (Optional) Preload the data before enabling the TX channel, so that the valid data can be transmitted immediately */
	// while (w_bytes == EXAMPLE_BUFF_SIZE) {
	// 	/* Here we load the target buffer repeatedly, until all the DMA buffers are preloaded */
	// 	ESP_ERROR_CHECK(i2s_channel_preload_data(tx_chan, w_buf, EXAMPLE_BUFF_SIZE, &w_bytes));
	// }

	/* Enable the TX channel */
	ESP_ERROR_CHECK(i2s_channel_enable(tx_chan));
	while (1) {
		/* Write i2s data */
		if (i2s_channel_write(tx_chan, w_buf, EXAMPLE_BUFF_SIZE, &w_bytes, 1000) == ESP_OK) {
			printf("*");
			fflush(stdout);

			/* Assign w_buf */
			for (int i = 0; i < EXAMPLE_BUFF_SIZE; i += 8) {
				w_buf[i]     = 0x12;
				w_buf[i + 1] = 0x34;
				w_buf[i + 2] = 0x56;
				w_buf[i + 3] = 0x78;

				w_buf[i + 4] = cnt;
				w_buf[i + 5] = cnt >> 8;
				w_buf[i + 6] = cnt >> 16;
				w_buf[i + 7] = cnt >> 24;

				cnt++;
			}

		} else {
			printf("Write Task: i2s write failed\n");
		}
		// vTaskDelay(1);
	}
	free(w_buf);
	vTaskDelete(NULL);
}

static void i2s_example_init_std_simplex(void)
{
	/* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
	 * The default configuration can be generated by the helper macro,
	 * it only requires the I2S controller id and I2S role
	 * The tx and rx channels here are registered on different I2S controller,
	 * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
	i2s_chan_config_t tx_chan_cfg = {
		.id = I2S,
		.role = I2S_ROLE_MASTER,
		.dma_desc_num = 6,
		.dma_frame_num = 240,
		.auto_clear = true,
	};
	ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

	/* Step 2: Setting the configurations of standard mode and initialize each channels one by one
	 * The slot configuration and clock configuration can be generated by the macros
	 * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
	 * They can help to specify the slot and clock configurations for initialization or re-configuring */
	i2s_std_config_t tx_std_cfg = {
		.clk_cfg  = {
			.sample_rate_hz = 200000,
			// .clk_src = SOC_MOD_CLK_PLL_F160M,
			.clk_src = SOC_MOD_CLK_APLL,
			.mclk_multiple = I2S_MCLK_MULTIPLE_128
		},
		.slot_cfg = {
			.data_bit_width = I2S_DATA_BIT_WIDTH_32BIT,
			.slot_bit_width = I2S_SLOT_BIT_WIDTH_AUTO,
			.slot_mode = I2S_SLOT_MODE_STEREO,
			.slot_mask = I2S_STD_SLOT_BOTH,
			.ws_width = 32,
			.ws_pol = false,
			.bit_shift = false,
			.msb_right = false
		},
		.gpio_cfg = {
			.mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
			.bclk = 14,
			.ws   = 15,
			.dout = 13,
			.din  = -1,
			.invert_flags = {
				.mclk_inv = false,
				.bclk_inv = false,
				.ws_inv   = false,
			},
		},
	};
	ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));

	rtc_clk_apll_coeff_set(0, 0, 0, 9);  // 1.6 us, 40 MHz

	I2S1.clkm_conf.clkm_div_num = 1;
	I2S1.clkm_conf.clkm_div_b = 0;
	I2S1.clkm_conf.clkm_div_a = 1;
	I2S1.clkm_conf.clk_en = 1;
	I2S1.clkm_conf.clka_en = 0;
}

void app_main(void)
{
	printf("Hello, this is an SPI - test, I2S version!\n");

	i2s_example_init_std_simplex();

	/* Step 3: Create writing and reading task, enable and start the channels */
	xTaskCreate(i2s_example_write_task, "i2s_example_write_task", 4096, NULL, 5, NULL);
}
