#include <stdint.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "esp_check.h"
#include "sdkconfig.h"
#include "soc/i2s_struct.h"
#include "soc/rtc.h"


#define EXAMPLE_BUFF_SIZE               1024 * 4

static i2s_chan_handle_t                tx_chan;        // I2S tx channel handler

static void i2s_example_write_task(void *args)
{
	uint8_t *w_buf = (uint8_t *)calloc(1, EXAMPLE_BUFF_SIZE);
	assert(w_buf);  // Check if w_buf allocation success

	/* Enable the TX channel */
	ESP_ERROR_CHECK(i2s_channel_enable(tx_chan));

	unsigned buf_id = 0;

	while (1) {
		for (int i = 0; i < EXAMPLE_BUFF_SIZE; i += 8) {
			w_buf[i + 7] = 0x12;
			w_buf[i + 6] = 0x34;
			w_buf[i + 5] = 0x56;

			w_buf[i + 4] = 0x78;
			w_buf[i + 3] = buf_id >> 16;
			w_buf[i + 2] = buf_id >> 8;

			w_buf[i + 1] = buf_id;
			w_buf[i] = 0x00;  // CS goes high here
		}

		/* Write i2s data */
		size_t w_bytes = EXAMPLE_BUFF_SIZE;
		if (!i2s_channel_write(tx_chan, w_buf, EXAMPLE_BUFF_SIZE, &w_bytes, 1000) == ESP_OK) {
			printf("Write Task: i2s write %d bytes\n", w_bytes);
		} else {
			printf("Write Task: i2s write failed\n");
		}

		buf_id++;
	}
	free(w_buf);
	vTaskDelete(NULL);
}

static void i2s_example_init_std_simplex(void)
{
	/* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
	 * The default configuration can be generated by the helper macro,
	 * it only requires the I2S controller id and I2S role
	 * The tx and rx channels here are registered on different I2S controller,
	 * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
	i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
	ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

	/* Step 2: Setting the configurations of standard mode and initialize each channels one by one
	 * The slot configuration and clock configuration can be generated by the macros
	 * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
	 * They can help to specify the slot and clock configurations for initialization or re-configuring */
	i2s_std_config_t tx_std_cfg = {
		.clk_cfg  = {
			.sample_rate_hz = 200000,
			// .clk_src = SOC_MOD_CLK_PLL_F160M,
			.clk_src = SOC_MOD_CLK_APLL,
			.mclk_multiple = I2S_MCLK_MULTIPLE_128
		},
		.slot_cfg = {
			.data_bit_width = I2S_DATA_BIT_WIDTH_32BIT,
			.slot_bit_width = I2S_SLOT_BIT_WIDTH_32BIT,
			.slot_mode = I2S_SLOT_MODE_STEREO,
			.slot_mask = I2S_STD_SLOT_BOTH,
			.ws_width = 1,
			.ws_pol = true,
			.bit_shift = true,
			.msb_right = false
		},
		.gpio_cfg = {
			.mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
			.bclk = 14,
			.ws   = 15,
			.dout = 13,
			.din  = -1,
			.invert_flags = {
				.mclk_inv = false,
				.bclk_inv = false,
				.ws_inv   = false,
			},
		},
	};
	ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));

	rtc_clk_apll_coeff_set(0, 0, 0, 9);  // 1.9 us
}

void app_main(void)
{
	printf("Hello, this is an SPI - test, I2S version!\n");

	i2s_example_init_std_simplex();

	/* Step 3: Create writing and reading task, enable and start the channels */
	xTaskCreate(i2s_example_write_task, "i2s_example_write_task", 4096, NULL, 5, NULL);
}
