name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v14

    - name: Verify emcc
      run: emcc -v
      
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: make
      working-directory: test_draw
      run: make test.html
