name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v14

    - name: clone
      uses: actions/checkout@v3

    - name: make
      working-directory: test_draw
      run: make wasm

    - name: configure-pages
      uses: actions/configure-pages@v5

    - name: upload-pages-artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: test_draw/dist

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy-pages
        id: deployment
        uses: actions/deploy-pages@v4
