name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v14
    
    - name: Verify
      run: emcc -v
      
    - name: make
      working-directory: ./test_draw
      run: make test.html
